zuul:
  sensitive-headers: 
  routes:
    myProduct:
      path: /myProduct/**
      serviceId: product
#      sensitiveHeaders:
#    product: /product/**
  ignored-patterns:
  - /**/product/listForOrder
management:
  endpoints:
    web:
      exposure:
        include: routes,filters

spring:
  redis:
    host: 192.168.205.10
    port: 6379
