spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Pa55Word
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.205.10
    port: 5672
    username: admin
    password: admin
