spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Pa55Word
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.205.10
    port: 6379
